#%RAML 1.0
title: Error-Handler-Test-API
baseUri: http://localhost:8081/

/error_1:
  get:
    responses: 
      200:
        body: 
          application/json: 
/error_2:
  get:
    responses:
      200: 
        body: 
          application/json:          